version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis

  worker:
    build: .
    command: python -m app.workers.message_worker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
